################################
# LEADER KEY
################################

map ctrl+a>shift+r load_config_file
map ctrl+a>shift+e launch --type=os-window nano ~/.config/kitty/kitty.conf
map ctrl+a>shift+d debug_config

################################
# TABS
################################

map ctrl+a>shift+c new_tab
map ctrl+a>shift+x close_tab

map ctrl+shift+left previous_tab
map ctrl+shift+right next_tab

map ctrl+shift+, move_tab_backward
map ctrl+shift+. move_tab_forward

map ctrl+a>shift+, set_tab_title

################################
# SPLITS
################################

map ctrl+a>- launch --location=hsplit --cwd=current
map ctrl+a>\\ launch --location=vsplit --cwd=current
map ctrl+a>x close_window

################################
# ZOOM
################################

map ctrl+a>shift+z toggle_zoom

################################
# WINDOW NAVIGATION
################################

map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down

map ctrl+a>shift+h neighboring_window left
map ctrl+a>shift+l neighboring_window right
map ctrl+a>shift+k neighboring_window up
map ctrl+a>shift+j neighboring_window down

################################
# MOVE WINDOWS
################################

map shift+left move_window left
map shift+right move_window right
map shift+up move_window up
map shift+down move_window down

################################
# RESIZE MODE
################################

map ctrl+shift+r start_resizing_window

map alt+n resize_window narrower
map alt+w resize_window wider
map alt+u resize_window taller
map alt+d resize_window shorter

map ctrl+home resize_window reset

################################
# FONT CONTROL
################################

map ctrl+equal change_font_size all +2
map ctrl+minus change_font_size all -2
map ctrl+0 change_font_size all 0