background #0b0616
foreground #d6d6ff

cursor #ff2bd6
cursor_text_color background

selection_background #3a2fff
selection_foreground #ffffff

color0 #0d0b1a
color1 #ff4d6d
color2 #00ffa6
color3 #ffe066
color4 #3a86ff
color5 #ff2bd6
color6 #2de2e6
color7 #e0e0ff

color8 #3b3355
color9 #ff6f91
color10 #00ffc8
color11 #fff275
color12 #6aa9ff
color13 #ff6bff
color14 #6fffe9
color15 #ffffff

active_border_color #ff2bd6
inactive_border_color #1f1a2e

tab_bar_edge top
